export const DENGLEMA_UPDATES = Object.freeze([
  {
    id: "update-log",
    date: "2026-09-30",
    category: "产品",
    emoji: "📝",
    title: "独立更新日志上线",
    summary: "24h 动态继续负责新鲜事，长期功能历史搬到独立 Changelog；支持按类别筛选并跳到对应 PR 或功能页。",
    pr: 51,
    href: "/updates",
  },
  {
    id: "daily-routes",
    date: "2026-09-30",
    category: "产品",
    emoji: "🗺️",
    title: "燃烧榜改成今日蹬况",
    summary: "榜单继续保留，但页面主叙事改成今日路线与分布，排名退到更低层级，减少 KPI 味。",
    pr: 52,
    href: "/leaderboards",
  },
  {
    id: "project-privacy",
    date: "2026-09-30",
    category: "隐私",
    emoji: "🔒",
    title: "Project 隐私模式",
    summary: "每个 Project 都可以公开原名、隐藏或设置公开别名；公共榜单和骑手详情统一应用隐私规则。",
    pr: 49,
    href: "/privacy",
  },
  {
    id: "ci-superseded-deploys",
    date: "2026-09-30",
    category: "基础设施",
    emoji: "🧹",
    title: "CI 会识别被新 main 超车的旧部署",
    summary: "旧 pipeline 被更新 commit 取代时改为 superseded，不再把正常部署竞态标成红灯。",
    pr: 50,
  },
  {
    id: "quota-emotion",
    date: "2026-09-30",
    category: "Rider Lab",
    emoji: "😵",
    title: "低额度情绪可自定义",
    summary: "额度压力继续只是趣味视觉，但现在可以选择 sweat、gloom 或 sleepy 等表现方式。",
    pr: 48,
    href: "/lab",
  },
  {
    id: "rider-lab",
    date: "2026-09-30",
    category: "个性化",
    emoji: "🧪",
    title: "Rider Lab 上线",
    summary: "开放个人随机口号，并建立人物、动作、工位和更多外观实验的统一入口；自己的工位也可以直接拖动。",
    pr: 46,
    href: "/lab",
  },
  {
    id: "transport-motion",
    date: "2026-09-30",
    category: "动画",
    emoji: "🛼",
    title: "交通工具动作继续补物理感",
    summary: "轮滑鞋和步行鞋真正跟随脚部动作，人物随机对白也统一显示在顶部 UI 之上。",
    pr: 43,
  },
  {
    id: "rider-message-indicator",
    date: "2026-09-30",
    category: "社交",
    emoji: "💬",
    title: "人物支持最近留言入口",
    summary: "发过留言的人会显示一个轻量的“…”入口，点击即可回看最近一句；新留言仍会自动冒泡。",
    pr: 40,
  },
  {
    id: "comment-bubbles",
    date: "2026-09-30",
    category: "社交",
    emoji: "🗨️",
    title: "留言进入人物气泡，动态显示头像",
    summary: "24h 动态里的 comment 会投影到人物气泡，用户事件也开始使用真实头像而不是统一图标。",
    pr: 39,
  },
  {
    id: "recent-reset",
    date: "2026-09-30",
    category: "Reset",
    emoji: "🎉",
    title: "最近 24h Reset 完成状态",
    summary: "顶部 Reset 提示可以显示当天最近一次已完成 reset；超过 24 小时后自动退回普通排期状态。",
    pr: 36,
  },
  {
    id: "plugin-0-1-17",
    date: "2026-09-30",
    category: "Plugin",
    emoji: "📦",
    title: "Codex Plugin 0.1.17",
    summary: "上传剩余额度、窗口与 reset 时间，让赛道可以表现额度压力，但不把它解释成工作质量。",
    href: "/plugin#upgrade-0-1-17",
  },
  {
    id: "plugin-0-1-16",
    date: "2026-09-30",
    category: "Plugin",
    emoji: "📦",
    title: "Codex Plugin 0.1.16",
    summary: "新增明确授权后的自动上传，可选 1h / 3h / 6h / 每天；手动上传继续保留。",
    href: "/plugin#upgrade-0-1-16",
  },
]);

export function publicDenglemaUpdates() {
  return DENGLEMA_UPDATES.map((item) => ({ ...item }));
}
